# Generated by Django 4.0.5 on 2022-12-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=200)),
                ('Phone_number', models.CharField(max_length=12, unique=True)),
                ('Email', models.EmailField(max_length=200, unique=True)),
                ('Age', models.CharField(max_length=2)),
                ('Blood_Group', models.CharField(max_length=300)),
                ('Last_donated', models.DateField()),
                ('Address', models.CharField(max_length=300)),
                ('City', models.CharField(max_length=300)),
                ('Pin_code', models.CharField(max_length=8)),
                ('State', models.CharField(max_length=300)),
            ],
        ),
    ]
